//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatieAppExam.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterService
    {
        public int IDMasterService { get; set; }
        public Nullable<int> IDService { get; set; }
        public Nullable<int> IDMaster { get; set; }
        public Nullable<int> IDDirection { get; set; }
    
        public virtual Direction Direction { get; set; }
        public virtual Master Master { get; set; }
        public virtual Service Service { get; set; }
    }
}
