//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatieAppExam.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatieDatabaseExamEntities1 : DbContext
    {
        public MatieDatabaseExamEntities1()
            : base("name=MatieDatabaseExamEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Direction> Direction { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<MasterQuality> MasterQuality { get; set; }
        public virtual DbSet<MasterService> MasterService { get; set; }
        public virtual DbSet<Queue> Queue { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
