//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatieAppExam.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public int IDQueue { get; set; }
        public Nullable<int> IDMaster { get; set; }
        public Nullable<int> IDUser { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual User User { get; set; }
    }
}
